[2024-04-22T06:37:11.975+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T06:37:12.070+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_payments manual__2024-04-22T06:33:02.563052+00:00 [queued]>
[2024-04-22T06:37:12.323+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_payments manual__2024-04-22T06:33:02.563052+00:00 [queued]>
[2024-04-22T06:37:12.330+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-22T06:37:12.478+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_payments> on 2024-04-22 06:33:02.563052+00:00
[2024-04-22T06:37:12.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_payments', 'manual__2024-04-22T06:33:02.563052+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmprjniycg2']
[2024-04-22T06:37:12.567+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask gcs_to_bq_payments
[2024-04-22T06:37:12.578+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3598) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T06:37:12.585+0000] {standard_task_runner.py:63} INFO - Started process 3631 to run task
[2024-04-22T06:37:12.776+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_payments manual__2024-04-22T06:33:02.563052+00:00 [running]> on host af114bcfa67a
[2024-04-22T06:37:14.468+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_payments' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T06:33:02.563052+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T06:33:02.563052+00:00'
[2024-04-22T06:37:14.477+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T06:37:14.508+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-22T06:37:14.554+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-22T06:37:14.556+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-04-22T06:37:14.911+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: order.olist_payments_dataset; using project "dataengineer-415510"
[2024-04-22T06:37:14.912+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dataengineer-415510', 'datasetId': 'order', 'tableId': 'olist_payments_dataset'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://swu-ds-525-112233/olist_payments_dataset.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-04-22T06:37:14.921+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_payments_2024_04_22T06_33_02_563052_00_00_d4bd57527ed71a9c4e6ad2068ccaaef0
[2024-04-22T06:37:18.890+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T06:37:18.893+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://swu-ds-525-112233/olist_payments_dataset.csv; reason: notFound, message: Not found: URI gs://swu-ds-525-112233/olist_payments_dataset.csv
[2024-04-22T06:37:18.906+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_payments, execution_date=20240422T063302, start_date=20240422T063712, end_date=20240422T063718
[2024-04-22T06:37:18.928+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 224 for task gcs_to_bq_payments (404 Not found: URI gs://swu-ds-525-112233/olist_payments_dataset.csv; reason: notFound, message: Not found: URI gs://swu-ds-525-112233/olist_payments_dataset.csv; 3631)
[2024-04-22T06:37:18.973+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T06:37:19.336+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T06:37:19.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
