[2024-04-14T05:57:09.103+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T05:57:09.115+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T05:57:09.121+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T05:57:09.121+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-14T05:57:09.135+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): create_tables> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T05:57:09.145+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp3l2v1usz']
[2024-04-14T05:57:09.146+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask create_tables
[2024-04-14T05:57:09.150+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=45302) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T05:57:09.150+0000] {standard_task_runner.py:63} INFO - Started process 45319 to run task
[2024-04-14T05:57:09.192+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_tables manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T05:57:09.431+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T05:57:09.432+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T05:57:09.432+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T05:57:09.432+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 58, in _create_table
    hook = PostgresHook(postgres_conn_id="my_gcs_conn")
           ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined
[2024-04-14T05:57:09.442+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=create_tables, execution_date=20240414T050956, start_date=20240414T055709, end_date=20240414T055709
[2024-04-14T05:57:09.456+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task create_tables (name 'PostgresHook' is not defined; 45319)
[2024-04-14T05:57:09.486+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T05:57:09.503+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T05:57:09.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
