[2024-04-18T08:28:03.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T08:28:03.747+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.load_data_into_new_table scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-18T08:28:03.773+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.load_data_into_new_table scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-18T08:28:03.774+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-18T08:28:03.826+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryInsertJobOperator): load_data_into_new_table> on 2024-04-16 00:00:00+00:00
[2024-04-18T08:28:03.905+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=776) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-18T08:28:03.909+0000] {standard_task_runner.py:63} INFO - Started process 870 to run task
[2024-04-18T08:28:03.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'load_data_into_new_table', 'scheduled__2024-04-16T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp8n6qjecg']
[2024-04-18T08:28:03.938+0000] {standard_task_runner.py:91} INFO - Job 182: Subtask load_data_into_new_table
[2024-04-18T08:28:04.061+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.load_data_into_new_table scheduled__2024-04-16T00:00:00+00:00 [running]> on host 2ce858e27684
[2024-04-18T08:28:04.264+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='load_data_into_new_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:00:00+00:00'
[2024-04-18T08:28:04.266+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T08:28:04.277+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-18T08:28:04.298+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-18T08:28:04.371+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': '\n            CREATE OR REPLACE TABLE `dataengineer-415510.order.Finance` AS\n            SELECT \n                customerid, \n                paymenttype\n            FROM `dataengineer-415510.order.dataset_order`\n            ', 'useLegacySql': False}}'
[2024-04-18T08:28:04.372+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_load_data_into_new_table_2024_04_16T00_00_00_00_00_68740613e9dc2be4f3506ef372a12dac
[2024-04-18T08:28:08.536+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T08:28:08.556+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=load_data_into_new_table, execution_date=20240416T000000, start_date=20240418T082803, end_date=20240418T082808
[2024-04-18T08:28:08.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-18T08:28:08.624+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-18T08:28:08.630+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
