[2024-04-14T10:16:43.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T10:16:43.803+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T10:15:09.605913+00:00 [queued]>
[2024-04-14T10:16:43.810+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T10:15:09.605913+00:00 [queued]>
[2024-04-14T10:16:43.810+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-14T10:16:43.833+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-04-14 10:15:09.605913+00:00
[2024-04-14T10:16:43.845+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=181714) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T10:16:43.846+0000] {standard_task_runner.py:63} INFO - Started process 181726 to run task
[2024-04-14T10:16:43.844+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'manual__2024-04-14T10:15:09.605913+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp5_jccf4q']
[2024-04-14T10:16:43.846+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask create_order_dataset
[2024-04-14T10:16:43.886+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset manual__2024-04-14T10:15:09.605913+00:00 [running]> on host 2ce858e27684
[2024-04-14T10:16:43.982+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T10:15:09.605913+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T10:15:09.605913+00:00'
[2024-04-14T10:16:43.986+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T10:16:43.992+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T10:16:43.997+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T10:16:44.042+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-04-14T10:16:44.043+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value dataengineer-415510.
[2024-04-14T10:16:44.043+0000] {bigquery.py:481} INFO - Creating dataset: order in project: dataengineer-415510 
[2024-04-14T10:16:44.469+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-04-14T10:16:44.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T10:16:44.498+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240414T101509, start_date=20240414T101643, end_date=20240414T101644
[2024-04-14T10:16:44.543+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T10:16:44.555+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class BigQueryExecuteQueryOperator. (This operator is deprecated. Please use `BigQueryInsertJobOperator`.)
[2024-04-14T10:16:44.567+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-14T10:16:44.576+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
