[2024-04-14T08:20:18.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T08:20:18.597+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:20:18.603+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:20:18.603+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 7
[2024-04-14T08:20:18.617+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T08:20:18.627+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=120437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T08:20:18.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4yx9k0s8']
[2024-04-14T08:20:18.628+0000] {standard_task_runner.py:63} INFO - Started process 120463 to run task
[2024-04-14T08:20:18.629+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask create_order_dataset
[2024-04-14T08:20:18.667+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T08:20:18.745+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T08:20:18.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T08:20:18.754+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T08:20:18.758+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T08:20:18.804+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-04-14T08:20:18.805+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value dataengineer-415510.
[2024-04-14T08:20:18.805+0000] {bigquery.py:481} INFO - Creating dataset: order in project: dataengineer-415510 
[2024-04-14T08:20:19.254+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-04-14T08:20:19.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T08:20:19.281+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240414T050956, start_date=20240414T082018, end_date=20240414T082019
[2024-04-14T08:20:19.324+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T08:20:19.333+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class BigQueryExecuteQueryOperator. (This operator is deprecated. Please use `BigQueryInsertJobOperator`.)
[2024-04-14T08:20:19.341+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-14T08:20:19.347+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
