[2024-04-14T05:57:05.867+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T05:57:05.879+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T05:57:05.885+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T05:57:05.885+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-14T05:57:05.900+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T05:57:05.910+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpr7b28qeh']
[2024-04-14T05:57:05.912+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask create_order_dataset
[2024-04-14T05:57:05.916+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=45254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T05:57:05.917+0000] {standard_task_runner.py:63} INFO - Started process 45261 to run task
[2024-04-14T05:57:05.952+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T05:57:06.188+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T05:57:06.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T05:57:06.195+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T05:57:06.200+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T05:57:06.244+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-04-14T05:57:06.245+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value dataengineer-415510.
[2024-04-14T05:57:06.245+0000] {bigquery.py:481} INFO - Creating dataset: order in project: dataengineer-415510 
[2024-04-14T05:57:06.733+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-04-14T05:57:06.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T05:57:06.810+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240414T050956, start_date=20240414T055705, end_date=20240414T055706
[2024-04-14T05:57:06.902+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T05:57:06.941+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-14T05:57:06.953+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
