[2024-04-26T16:07:30.885+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T16:07:30.941+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T16:07:31.010+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T16:07:31.010+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-26T16:07:31.086+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): git_install_task> on 2024-04-25 00:00:00+00:00
[2024-04-26T16:07:31.122+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt', 'git_install_task', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/bq_dbt.py', '--cfg-path', '/tmp/tmp8hlt1w98']
[2024-04-26T16:07:31.124+0000] {standard_task_runner.py:91} INFO - Job 372: Subtask git_install_task
[2024-04-26T16:07:31.116+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=110316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T16:07:31.128+0000] {standard_task_runner.py:63} INFO - Started process 110341 to run task
[2024-04-26T16:07:31.388+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [running]> on host b619dce40a27
[2024-04-26T16:07:31.771+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt' AIRFLOW_CTX_TASK_ID='git_install_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-26T16:07:31.775+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T16:07:31.785+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-26T16:07:31.786+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo apt-get install git -y']
[2024-04-26T16:07:31.895+0000] {subprocess.py:86} INFO - Output:
[2024-04-26T16:07:32.554+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2024-04-26T16:07:32.555+0000] {subprocess.py:93} INFO - sudo: a password is required
[2024-04-26T16:07:32.556+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-26T16:07:32.556+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T16:07:32.567+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-26T16:07:32.570+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt, task_id=git_install_task, execution_date=20240425T000000, start_date=20240426T160730, end_date=20240426T160732
[2024-04-26T16:07:32.584+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 372 for task git_install_task (Bash command failed. The command returned a non-zero exit code 1.; 110341)
[2024-04-26T16:07:32.620+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T16:07:32.632+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T16:07:32.639+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
