[2024-04-14T09:00:03.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T09:00:03.029+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_Finance manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T09:00:03.036+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_Finance manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T09:00:03.037+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-04-14T09:00:03.067+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_Finance> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T09:00:03.078+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=141437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T09:00:03.078+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_Finance', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpuqhuwqbr']
[2024-04-14T09:00:03.079+0000] {standard_task_runner.py:63} INFO - Started process 141439 to run task
[2024-04-14T09:00:03.079+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask create_Finance
[2024-04-14T09:00:03.124+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_Finance manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T09:00:03.194+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_Finance' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T09:00:03.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T09:00:03.196+0000] {bigquery.py:1246} INFO - Executing: ALTER TABLE
  `dataengineer-415510.order.Finance` ADD COLUMN
IF NOT EXISTS Finance STRING;
CREATE OR REPLACE TABLE
  `dataengineer-415510.order_bazilian.csv` 
SELECT
  'No',
  'paymenttype',
FROM
  `dataengineer-415510.order.Finance`;
[2024-04-14T09:00:03.203+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T09:00:03.208+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T09:00:03.209+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/google/cloud/operators/bigquery.py:1254 AirflowProviderDeprecationWarning: Call to deprecated method run_query. (Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.insert_job`)
[2024-04-14T09:00:03.256+0000] {bigquery.py:1613} INFO - Inserting job ***_1713085203255976_c79db5837e566f84ca9eac3a8c445878
[2024-04-14T09:00:03.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T09:00:03.571+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1254, in execute
    self.job_id = self.hook.run_query(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2258, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1619, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected end of input but got keyword SELECT at [6:1]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got keyword SELECT at [6:1]

Location: asia-southeast1
Job ID: airflow_1713085203255976_c79db5837e566f84ca9eac3a8c445878

[2024-04-14T09:00:03.580+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=create_Finance, execution_date=20240414T050956, start_date=20240414T090003, end_date=20240414T090003
[2024-04-14T09:00:03.593+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task create_Finance (400 Syntax error: Expected end of input but got keyword SELECT at [6:1]; reason: invalidQuery, location: query, message: Syntax error: Expected end of input but got keyword SELECT at [6:1]

Location: asia-southeast1
Job ID: airflow_1713085203255976_c79db5837e566f84ca9eac3a8c445878
; 141439)
[2024-04-14T09:00:03.615+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T09:00:03.628+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T09:00:03.634+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
